# Generated by Django 5.2 on 2025-04-28 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "menu_name",
                    models.CharField(help_text="Название меню", max_length=120),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "url",
                    models.CharField(blank=True, help_text="named URL", max_length=200),
                ),
                (
                    "named_url",
                    models.CharField(
                        blank=True, help_text="Имя именованного URL", max_length=100
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="menu.menuitem",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
